### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by papipons** [oz123/django-pdfviewer#1]
Hi! Greetings! I am very sorry for this. I don't know any other ways to contact you. I am just wondering on how to use this library? I am looking for days on how to display my PDF files in my html templates. I am using django, as of now, I am converting every pages of the PDF to png, which takes a lot of time and a lot of space. I really need some help right now. >.< .

**Comment by oz123** [comment]
@shinjimaru01 My project is not a library. It's a django-web application which I don't maintain actively. 
As it say in the description, it's more or less doing what you are doing:

```
     render pdf pages as png images
```

But, rendering does not have to be done on a live system. You can do this on another system and just 
display the rendered PNG images.
Can you please update your profile to include an E-Mail ? Other wise you are invited also to contact me per email. 

The library you are using to render pdf to png, will also determine the performance.
